config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts
  resources :microposts do
    member do
      post 'likerelationships',   to: 'likerelationships#create'
      delete 'likerelationships', to: 'likerelationships#destroy'
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :users do
    member do
      get :followings
      get :followers
      get :likerelationships
    end
  end

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  
  
  mount_uploader :image, ImageUploader

  ##こっからお気に入り機能
  has_many :liked_likerelationships, class_name: "Likerelationship",
                                foreign_key: "liked_id",
                                dependent: :destroy
  has_many :liked_users, through: :liked_likerelationships, source: :like
  
  
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create]

  
  def create
    
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "投稿しました"
      redirect_to root_url
    else
      @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc)# この行を追加
      flash[:warning] = '投稿に失敗しました！'
      
     #binding.pry
     redirect_to root_url
     # render 'static_pages/home'
    end
  end
  
  def destroy
    @micropost = current_user.microposts.find_by(id: params[:id])
    return redirect_to root_url if @micropost.nil?
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end
  
  
  private
  def micropost_params
    
    params.require(:micropost).permit(:content,:image)
  end
end

app/views/microposts/_like.html.erb
<%= form_for(current_user.like_likerelationships.build, url: likerelationships_micropost_path(micropost.id), html: {id: "like-#{micropost.id}"},  remote: true) do |f| %>
  <div><%= hidden_field_tag :like_id, micropost %>
  </div>
  <%= f.submit "Like", class: "btn btn-primary" %>
<% end %>

app/views/microposts/_like_form.html.erb
<% if current_user != @user %>
  <div id="like_form">
  <% if current_user.like?(micropost) %>
    <%= render 'microposts/unlike', micropost: micropost  %>
  <% else %>
    <%= render 'microposts/like', micropost: micropost   %>
  <% end %>
  </div>
<% end %>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    <%= time_ago_in_words(micropost.created_at) %> 前の投稿です
    <% if current_user == micropost.user %>
      <%= link_to "削除", micropost, method: :delete,
                                       data: { confirm: "ええんか？" } %>
    <% end %>
    
  </span>
  <% if micropost.image? %>
    <div class="thumbnail">
      <%= image_tag micropost.image.url %>
    </div>
  <% end %>
  <%= render 'microposts/like_form', micropost: micropost  %>
</li>

app/views/microposts/_unlike.html.erb
<%= form_for(current_user.like_likerelationships.find_by(liked_id: micropost.id),
             url: likerelationships_micropost_path(micropost.id),
             html: { method: :delete ,id: "like-#{micropost.id}"},
             remote: true) do |f| %>
             
  <%= f.submit "Unlike", class: "btn" %>
<% end %>